name: Build .NET App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/SomeActionApi/SomeActionApi.csproj
      
    - name: Build
      run: dotnet build src/SomeActionApi/SomeActionApi.csproj --no-restore
      
    - name: Test
      run: dotnet test src/SomeActionApi/SomeActionApi.csproj --no-build --verbosity normal

    - name: Publish
      run: dotnet publish src/SomeActionApi/SomeActionApi.csproj -c Release -o publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: publish/ 