name: Build Docker Image

on:
  workflow_run:
    workflows: ["Build .NET App"]
    types:
      - completed
    branches: [ "master" ]

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
    - uses: actions/checkout@v4

    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: Build .NET App
        name: app-build
        path: publish/
        run_id: ${{ github.event.workflow_run.id }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/SomeActionApi/Dockerfile
        push: false
        tags: someactionapi:latest
        load: true 